# Generated by Django 5.1.4 on 2025-03-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=50, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount_yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Custom', 'Custom')], max_length=50)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rent_increase_date', models.DateField(blank=True, null=True)),
                ('increase_type', models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Percent', 'Percent')], max_length=10, null=True)),
                ('increase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.billboard')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rentagreement')),
            ],
        ),
    ]
