# Generated by Django 5.1.7 on 2025-03-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_billboard_created_at_billboard_landlord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentagreement',
            name='increase_type',
        ),
        migrations.RemoveField(
            model_name='rentagreement',
            name='payment_frequency',
        ),
        migrations.AddField(
            model_name='rentagreement',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentagreement',
            name='last_paid_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentagreement',
            name='next_payable_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentagreement',
            name='payment_frequency_months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
