# Generated by Django 5.1.7 on 2025-03-10 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_remove_rentagreement_increase_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentagreement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentagreement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
