# Generated by Django 5.1.7 on 2025-03-10 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rentagreement_created_at_rentagreement_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentagreement',
            name='agreement_number',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
