# Generated by Django 5.1.7 on 2025-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_rentagreement_agreement_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentagreement',
            name='agreement_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
