# Generated by Django 5.1.7 on 2025-03-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_alter_rentagreement_agreement_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentagreement',
            name='last_paid_month',
        ),
        migrations.RemoveField(
            model_name='rentagreement',
            name='next_payable_month',
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='rent.rentagreement')),
            ],
        ),
    ]
