# Generated by Django 5.1.7 on 2025-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_remove_rentagreement_last_paid_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
