# Generated by Django 5.1.7 on 2025-03-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_installment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
