# Generated by Django 5.1.7 on 2025-03-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_alter_landlord_address_alter_landlord_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
