# Generated by Django 5.1.7 on 2025-03-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_alter_billboard_area_alter_billboard_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentagreement',
            name='landlord',
        ),
    ]
